#!/bin/bash
# rome_cleanup.sh [PROJECT_ID] [CLEANUP_MODE]
# ROME Project Cleanup - Remove artifacts and prepare delivery

PROJECT_ID=$1
CLEANUP_MODE=${2:-"standard"} # standard|aggressive|preserve

if [ -z "$PROJECT_ID" ]; then
    echo "Usage: $0 [PROJECT_ID] [CLEANUP_MODE]"
    echo "Modes: standard (default) | aggressive | preserve"
    echo "Example: $0 ROME-2025-0722-1430-FARM-WEATHER standard"
    exit 1
fi

ROME_DIR="/Users/will/flutterProjects/Exercises/july/zz_robot_army/ROME"

echo "🧹 ROME Project Cleanup"
echo "======================"
echo "Project: $PROJECT_ID" 
echo "Mode: $CLEANUP_MODE"

cd "$ROME_DIR" || exit 1

# Validate project exists
if [ ! -f "PROJECT/project_metadata.json" ]; then
    echo "❌ Error: Project metadata not found"
    exit 1
fi

# Create delivery package function
create_delivery_package() {
    local DELIVERY_NAME="ROME-DELIVERY-${PROJECT_ID}-$(date +%Y%m%d).tar.gz"
    
    echo "📦 Creating delivery package..."
    
    # Create temporary directory for delivery content
    local DELIVERY_TEMP="/tmp/rome_delivery_$$"
    mkdir -p "$DELIVERY_TEMP"
    
    # Copy production-ready files
    echo "  📋 Including production source code..."
    if [ -d "../PROJECT/SOURCE" ]; then
        mkdir -p "$DELIVERY_TEMP/source"
        cp -r ../PROJECT/SOURCE/* "$DELIVERY_TEMP/source/" 2>/dev/null || true
        # Remove development files
        rm -rf "$DELIVERY_TEMP/source/node_modules"
        rm -f "$DELIVERY_TEMP/source/.env*"
        rm -f "$DELIVERY_TEMP/source"/*.log
    fi
    
    echo "  📋 Including documentation..."
    # Copy essential documentation
    [ -f "PROJECT/SYSTEM_ARCHITECTURE.md" ] && cp "PROJECT/SYSTEM_ARCHITECTURE.md" "$DELIVERY_TEMP/"
    [ -f "PROJECT/API_DOCUMENTATION.md" ] && cp "PROJECT/API_DOCUMENTATION.md" "$DELIVERY_TEMP/"
    [ -f "PROJECT/DEPLOYMENT_GUIDE.md" ] && cp "PROJECT/DEPLOYMENT_GUIDE.md" "$DELIVERY_TEMP/"
    [ -f "PROJECT/project_metadata.json" ] && cp "PROJECT/project_metadata.json" "$DELIVERY_TEMP/"
    
    # Copy test results if available
    if [ -f "PROJECT/dev/test_results.md" ]; then
        echo "  📋 Including test results..."
        cp "PROJECT/dev/test_results.md" "$DELIVERY_TEMP/"
    fi
    
    # Create README for delivery
    cat > "$DELIVERY_TEMP/README.md" << EOF
# ${PROJECT_ID} - Delivery Package

## Contents
- \`source/\` - Production-ready source code
- \`SYSTEM_ARCHITECTURE.md\` - Technical architecture
- \`API_DOCUMENTATION.md\` - API specifications  
- \`DEPLOYMENT_GUIDE.md\` - Deployment instructions
- \`project_metadata.json\` - Project information

## Deployment
See DEPLOYMENT_GUIDE.md for setup instructions.

## Generated by ROME Methodology
Delivered: $(date -Iseconds)
EOF
    
    # Create delivery archive
    tar -czf "completed_projects/$DELIVERY_NAME" -C "$DELIVERY_TEMP" .
    rm -rf "$DELIVERY_TEMP"
    
    echo "  ✅ Delivery package: completed_projects/$DELIVERY_NAME"
    echo "  📊 Package size: $(du -sh completed_projects/$DELIVERY_NAME | cut -f1)"
}

# Create directories if they don't exist
mkdir -p completed_projects

# Execute cleanup based on mode
case $CLEANUP_MODE in
  "standard")
    echo "🧹 Standard cleanup - removing development artifacts..."
    
    # Remove robot activity logs but keep main project logs
    rm -f ../rodeo_*/robot_activity_*.log
    rm -f ../rodeo_*/PROJECT/dev/robot_activity_*.log.bak
    
    # Remove development dependencies
    if [ -d "../PROJECT/SOURCE/node_modules" ]; then
        echo "  🗑️  Removing node_modules..."
        rm -rf ../PROJECT/SOURCE/node_modules
    fi
    
    # Remove local environment files
    rm -f ../PROJECT/SOURCE/.env.local
    rm -f ../PROJECT/SOURCE/.env.development
    
    # Remove temporary files
    find . -name "*.tmp" -delete 2>/dev/null
    find . -name "*.bak" -delete 2>/dev/null
    find . -name ".DS_Store" -delete 2>/dev/null
    
    echo "  ✅ Standard cleanup complete"
    ;;
    
  "aggressive") 
    echo "🧹 Aggressive cleanup - removing all development artifacts..."
    
    # Remove all robot workspaces
    echo "  🗑️  Removing robot workspaces..."
    rm -rf ../rodeo_*
    
    # Remove all development tracking
    echo "  🗑️  Removing development tracking..."
    rm -rf PROJECT/dev/
    
    # Remove all log files from source
    find ../PROJECT/SOURCE -name "*.log" -delete 2>/dev/null
    
    # Remove build artifacts
    rm -rf ../PROJECT/SOURCE/dist
    rm -rf ../PROJECT/SOURCE/build
    rm -rf ../PROJECT/SOURCE/.cache
    
    echo "  ⚠️  Aggressive cleanup complete - project no longer resumable"
    ;;
    
  "preserve")
    echo "🧹 Preserve mode - minimal cleanup..."
    
    # Only remove temporary files
    find . -name "*.tmp" -delete 2>/dev/null
    find . -name "*.bak" -delete 2>/dev/null
    find . -name ".DS_Store" -delete 2>/dev/null
    
    echo "  ✅ Preserve cleanup complete - project fully intact"
    ;;
    
  *)
    echo "❌ Error: Invalid cleanup mode: $CLEANUP_MODE"
    echo "Valid modes: standard, aggressive, preserve"
    exit 1
    ;;
esac

# Create delivery package for standard and aggressive modes
if [ "$CLEANUP_MODE" != "preserve" ]; then
    create_delivery_package
fi

# Update project metadata status
echo "📝 Updating project status..."
if command -v jq >/dev/null 2>&1; then
    case $CLEANUP_MODE in
        "aggressive")
            NEW_STATUS="archived"
            ;;
        "standard")
            NEW_STATUS="completed"
            ;;
        "preserve")
            NEW_STATUS="completed"
            ;;
    esac
    
    jq --arg status "$NEW_STATUS" --arg mode "$CLEANUP_MODE" \
       '.status = $status | .lifecycle.cleaned = now | .lifecycle.cleaned |= strftime("%Y-%m-%dT%H:%M:%SZ") | .cleanupMode = $mode' \
       PROJECT/project_metadata.json > PROJECT/project_metadata.json.tmp && \
    mv PROJECT/project_metadata.json.tmp PROJECT/project_metadata.json
    
    echo "  📝 Project status updated to: $NEW_STATUS"
fi

echo ""
echo "✅ Cleanup complete for $PROJECT_ID"
echo "🎯 Cleanup mode: $CLEANUP_MODE"

# Show summary
case $CLEANUP_MODE in
    "standard")
        echo "📦 Delivery package created in completed_projects/"
        echo "🔄 Project can still be rehydrated if needed"
        ;;
    "aggressive") 
        echo "📦 Delivery package created in completed_projects/"
        echo "⚠️  Project cannot be resumed (robot workspaces removed)"
        ;;
    "preserve")
        echo "💾 Project preserved with minimal cleanup"
        echo "🔄 Project fully resumable"
        ;;
esac